# Generated by Django 3.0.4 on 2020-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passengers', models.PositiveIntegerField()),
                ('fuel_consumption', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flight_time', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'zipairline',
                'ordering': ['airplane_id'],
            },
        ),
    ]
